services:
  redis:
    image: redis:7
    ports:
      - "6379:6379"
    restart: always
  db:
    image: postgres:15
    container_name: blueprint-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: appdb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    depends_on:
      - redis

  api:
    container_name: blueprint-api
    build:
      context: ./api
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app
      - /app/node_modules
    env_file:
      - ./.env
    depends_on:
      - db
    command: sh -c "npm run migration:up && npx ts-node scripts/loadTranscript.ts && npm run start:dev"

  client:
    container_name: blueprint-client
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "5173:5173"
    volumes:
      - ./client:/app
      - client_node_modules:/app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000
    depends_on:
      - api

volumes:
  pgdata:
  client_node_modules:
